# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\employee_health.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1540, 1198)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 1201, 1041))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 1171, 1011))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.splitter = QtWidgets.QSplitter(self.groupBox)
        self.splitter.setGeometry(QtCore.QRect(20, 120, 361, 231))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.First_Name_input = QtWidgets.QLineEdit(self.layoutWidget)
        self.First_Name_input.setObjectName("First_Name_input")
        self.verticalLayout.addWidget(self.First_Name_input)
        self.Department_combo = QtWidgets.QComboBox(self.layoutWidget)
        self.Department_combo.setObjectName("Department_combo")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.verticalLayout.addWidget(self.Department_combo)
        self.Fit_testing_checkbox = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Fit_testing_checkbox.setFont(font)
        self.Fit_testing_checkbox.setObjectName("Fit_testing_checkbox")
        self.verticalLayout.addWidget(self.Fit_testing_checkbox)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setGeometry(QtCore.QRect(40, 540, 951, 431))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.Fit_testing_date = QtWidgets.QDateEdit(self.groupBox)
        self.Fit_testing_date.setGeometry(QtCore.QRect(200, 360, 181, 22))
        self.Fit_testing_date.setCalendarPopup(True)
        self.Fit_testing_date.setDate(QtCore.QDate(2021, 2, 1))
        self.Fit_testing_date.setObjectName("Fit_testing_date")
        self.PPE_audit_date = QtWidgets.QDateEdit(self.groupBox)
        self.PPE_audit_date.setGeometry(QtCore.QRect(590, 360, 231, 22))
        self.PPE_audit_date.setCalendarPopup(True)
        self.PPE_audit_date.setDate(QtCore.QDate(2021, 2, 1))
        self.PPE_audit_date.setObjectName("PPE_audit_date")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 360, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(410, 360, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.splitter_2 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_2.setGeometry(QtCore.QRect(350, 20, 230, 28))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.Search_input = QtWidgets.QLineEdit(self.splitter_2)
        self.Search_input.setObjectName("Search_input")
        self.Search_btn = QtWidgets.QPushButton(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Search_btn.setFont(font)
        self.Search_btn.setObjectName("Search_btn")
        self.splitter_3 = QtWidgets.QSplitter(self.groupBox)
        self.splitter_3.setGeometry(QtCore.QRect(400, 120, 421, 231))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.splitter_3)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.layoutWidget_3 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Last_name_input = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.Last_name_input.setObjectName("Last_name_input")
        self.verticalLayout_5.addWidget(self.Last_name_input)
        self.Start_Date = QtWidgets.QDateEdit(self.layoutWidget_3)
        self.Start_Date.setObjectName("Start_Date")
        self.verticalLayout_5.addWidget(self.Start_Date)
        self.PPE_Audit_checkbox = QtWidgets.QCheckBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.PPE_Audit_checkbox.setFont(font)
        self.PPE_Audit_checkbox.setObjectName("PPE_Audit_checkbox")
        self.verticalLayout_5.addWidget(self.PPE_Audit_checkbox)
        self.Annual_complete_date = QtWidgets.QDateEdit(self.layoutWidget_3)
        self.Annual_complete_date.setCalendarPopup(True)
        self.Annual_complete_date.setDate(QtCore.QDate(2021, 2, 1))
        self.Annual_complete_date.setObjectName("Annual_complete_date")
        self.verticalLayout_5.addWidget(self.Annual_complete_date)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(20, 410, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(190, 410, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(590, 410, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.Save_btn = QtWidgets.QPushButton(self.groupBox)
        self.Save_btn.setGeometry(QtCore.QRect(420, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Save_btn.setFont(font)
        self.Save_btn.setObjectName("Save_btn")
        self.load_btn = QtWidgets.QPushButton(self.groupBox)
        self.load_btn.setGeometry(QtCore.QRect(530, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.load_btn.setFont(font)
        self.load_btn.setObjectName("load_btn")
        self.delete_btn = QtWidgets.QPushButton(self.groupBox)
        self.delete_btn.setGeometry(QtCore.QRect(640, 480, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.delete_btn.setFont(font)
        self.delete_btn.setObjectName("delete_btn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1540, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.actionExit.triggered.connect(MainWindow.close)
        self.Fit_testing_checkbox.clicked.connect(self.Fit_testing_date.show)
        self.delete_btn.clicked.connect(self.tableWidget.deleteLater)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Department"))
        self.label_3.setText(_translate("MainWindow", "Fit Testing"))
        self.Department_combo.setItemText(0, _translate("MainWindow", "Administration"))
        self.Department_combo.setItemText(1, _translate("MainWindow", "Behavioral Health"))
        self.Department_combo.setItemText(2, _translate("MainWindow", "Dental"))
        self.Department_combo.setItemText(3, _translate("MainWindow", "Environmental Services"))
        self.Department_combo.setItemText(4, _translate("MainWindow", "Facilities"))
        self.Department_combo.setItemText(5, _translate("MainWindow", "Finance"))
        self.Department_combo.setItemText(6, _translate("MainWindow", "Health Promotion"))
        self.Department_combo.setItemText(7, _translate("MainWindow", "Information Technology"))
        self.Department_combo.setItemText(8, _translate("MainWindow", "Laboratory"))
        self.Department_combo.setItemText(9, _translate("MainWindow", "Medical Records"))
        self.Department_combo.setItemText(10, _translate("MainWindow", "Office of Environmental Health"))
        self.Department_combo.setItemText(11, _translate("MainWindow", "Optometry"))
        self.Department_combo.setItemText(12, _translate("MainWindow", "Patient Business Office"))
        self.Department_combo.setItemText(13, _translate("MainWindow", "Pharmacy"))
        self.Department_combo.setItemText(14, _translate("MainWindow", "Physical Therapy"))
        self.Department_combo.setItemText(15, _translate("MainWindow", "Primary Care"))
        self.Department_combo.setItemText(16, _translate("MainWindow", "Property and Supply"))
        self.Department_combo.setItemText(17, _translate("MainWindow", "Publich Health"))
        self.Department_combo.setItemText(18, _translate("MainWindow", "Purchased Referred Care"))
        self.Department_combo.setItemText(19, _translate("MainWindow", "Quality"))
        self.Department_combo.setItemText(20, _translate("MainWindow", "Security"))
        self.Department_combo.setItemText(21, _translate("MainWindow", "Social Services"))
        self.Fit_testing_checkbox.setText(_translate("MainWindow", "Yes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Department"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Start Date"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Annual Training Complete"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Fit Testing"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Audit"))
        self.label_2.setText(_translate("MainWindow", "Fit Testing Date"))
        self.label_8.setText(_translate("MainWindow", "PPE Audit Date"))
        self.Search_btn.setText(_translate("MainWindow", "Search"))
        self.label_6.setText(_translate("MainWindow", "Last Name"))
        self.label_7.setText(_translate("MainWindow", "Start Date"))
        self.label_9.setText(_translate("MainWindow", "PPE Audit"))
        self.label.setText(_translate("MainWindow", "Annual Complete"))
        self.PPE_Audit_checkbox.setText(_translate("MainWindow", "Yes"))
        self.label_10.setText(_translate("MainWindow", "Model #"))
        self.Save_btn.setText(_translate("MainWindow", "Save"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        self.delete_btn.setText(_translate("MainWindow", "Delete"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Employee info"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Reports"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "test"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setStatusTip(_translate("MainWindow", "Click to exit application"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

