# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'employee_healthfaMxao.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1540, 1198)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 40, 1201, 1041))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 1171, 1011))
        self.splitter = QSplitter(self.groupBox)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(20, 120, 361, 231))
        self.splitter.setOrientation(Qt.Horizontal)
        self.verticalLayoutWidget = QWidget(self.splitter)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(u"label_5")
        font = QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)

        self.verticalLayout_2.addWidget(self.label_5)

        self.label_4 = QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font)

        self.verticalLayout_2.addWidget(self.label_4)

        self.label_3 = QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font)

        self.verticalLayout_2.addWidget(self.label_3)

        self.splitter.addWidget(self.verticalLayoutWidget)
        self.layoutWidget = QWidget(self.splitter)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.First_Name_input = QLineEdit(self.layoutWidget)
        self.First_Name_input.setObjectName(u"First_Name_input")

        self.verticalLayout.addWidget(self.First_Name_input)

        self.Department_combo = QComboBox(self.layoutWidget)
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.addItem("")
        self.Department_combo.setObjectName(u"Department_combo")

        self.verticalLayout.addWidget(self.Department_combo)

        self.Fit_testing_checkbox = QCheckBox(self.layoutWidget)
        self.Fit_testing_checkbox.setObjectName(u"Fit_testing_checkbox")
        self.Fit_testing_checkbox.setFont(font)

        self.verticalLayout.addWidget(self.Fit_testing_checkbox)

        self.splitter.addWidget(self.layoutWidget)
        self.tableWidget = QTableWidget(self.groupBox)
        if (self.tableWidget.columnCount() < 6):
            self.tableWidget.setColumnCount(6)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, __qtablewidgetitem5)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(20, 530, 951, 431))
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(55)
        self.tableWidget.horizontalHeader().setProperty("showSortIndicator", True)
        self.Fit_testing_date = QDateEdit(self.groupBox)
        self.Fit_testing_date.setObjectName(u"Fit_testing_date")
        self.Fit_testing_date.setGeometry(QRect(200, 360, 181, 22))
        self.Fit_testing_date.setCalendarPopup(True)
        self.Fit_testing_date.setDate(QDate(2021, 2, 1))
        self.PPE_audit_date = QDateEdit(self.groupBox)
        self.PPE_audit_date.setObjectName(u"PPE_audit_date")
        self.PPE_audit_date.setGeometry(QRect(590, 360, 231, 22))
        self.PPE_audit_date.setCalendarPopup(True)
        self.PPE_audit_date.setDate(QDate(2021, 2, 1))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 360, 171, 31))
        self.label_2.setFont(font)
        self.label_8 = QLabel(self.groupBox)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(410, 360, 171, 31))
        self.label_8.setFont(font)
        self.splitter_2 = QSplitter(self.groupBox)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setGeometry(QRect(350, 20, 230, 28))
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.Search_input = QLineEdit(self.splitter_2)
        self.Search_input.setObjectName(u"Search_input")
        self.splitter_2.addWidget(self.Search_input)
        self.Search_btn = QPushButton(self.splitter_2)
        self.Search_btn.setObjectName(u"Search_btn")
        font1 = QFont()
        font1.setPointSize(11)
        self.Search_btn.setFont(font1)
        self.splitter_2.addWidget(self.Search_btn)
        self.splitter_3 = QSplitter(self.groupBox)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setGeometry(QRect(400, 120, 421, 231))
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.verticalLayoutWidget_3 = QWidget(self.splitter_3)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayout_6 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.verticalLayoutWidget_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setFont(font)

        self.verticalLayout_6.addWidget(self.label_6)

        self.label_7 = QLabel(self.verticalLayoutWidget_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setFont(font)

        self.verticalLayout_6.addWidget(self.label_7)

        self.label_9 = QLabel(self.verticalLayoutWidget_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setFont(font)

        self.verticalLayout_6.addWidget(self.label_9)

        self.label = QLabel(self.verticalLayoutWidget_3)
        self.label.setObjectName(u"label")
        self.label.setFont(font)

        self.verticalLayout_6.addWidget(self.label)

        self.splitter_3.addWidget(self.verticalLayoutWidget_3)
        self.layoutWidget_3 = QWidget(self.splitter_3)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.verticalLayout_5 = QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.Last_name_input = QLineEdit(self.layoutWidget_3)
        self.Last_name_input.setObjectName(u"Last_name_input")

        self.verticalLayout_5.addWidget(self.Last_name_input)

        self.Start_Date = QDateEdit(self.layoutWidget_3)
        self.Start_Date.setObjectName(u"Start_Date")

        self.verticalLayout_5.addWidget(self.Start_Date)

        self.PPE_Audit_checkbox = QCheckBox(self.layoutWidget_3)
        self.PPE_Audit_checkbox.setObjectName(u"PPE_Audit_checkbox")
        self.PPE_Audit_checkbox.setFont(font)

        self.verticalLayout_5.addWidget(self.PPE_Audit_checkbox)

        self.Annual_complete_date = QDateEdit(self.layoutWidget_3)
        self.Annual_complete_date.setObjectName(u"Annual_complete_date")
        self.Annual_complete_date.setCalendarPopup(True)
        self.Annual_complete_date.setDate(QDate(2021, 2, 1))

        self.verticalLayout_5.addWidget(self.Annual_complete_date)

        self.splitter_3.addWidget(self.layoutWidget_3)
        self.label_10 = QLabel(self.groupBox)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 410, 171, 31))
        self.label_10.setFont(font)
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(190, 410, 191, 31))
        self.lineEdit_2 = QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(590, 410, 191, 31))
        self.Save_btn = QPushButton(self.groupBox)
        self.Save_btn.setObjectName(u"Save_btn")
        self.Save_btn.setGeometry(QRect(420, 480, 101, 31))
        self.Save_btn.setFont(font)
        self.load_btn = QPushButton(self.groupBox)
        self.load_btn.setObjectName(u"load_btn")
        self.load_btn.setGeometry(QRect(530, 480, 101, 31))
        self.load_btn.setFont(font)
        self.delete_btn = QPushButton(self.groupBox)
        self.delete_btn.setObjectName(u"delete_btn")
        self.delete_btn.setGeometry(QRect(640, 480, 101, 31))
        self.delete_btn.setFont(font)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1540, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.actionExit.triggered.connect(MainWindow.close)
        self.Fit_testing_checkbox.clicked.connect(self.Fit_testing_date.show)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
#if QT_CONFIG(statustip)
        self.actionExit.setStatusTip(QCoreApplication.translate("MainWindow", u"Click to exit application", None))
#endif // QT_CONFIG(statustip)
        self.groupBox.setTitle("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"First Name", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Department", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Fit Testing", None))
        self.Department_combo.setItemText(0, QCoreApplication.translate("MainWindow", u"Administration", None))
        self.Department_combo.setItemText(1, QCoreApplication.translate("MainWindow", u"Behavioral Health", None))
        self.Department_combo.setItemText(2, QCoreApplication.translate("MainWindow", u"Dental", None))
        self.Department_combo.setItemText(3, QCoreApplication.translate("MainWindow", u"Environmental Services", None))
        self.Department_combo.setItemText(4, QCoreApplication.translate("MainWindow", u"Facilities", None))
        self.Department_combo.setItemText(5, QCoreApplication.translate("MainWindow", u"Finance", None))
        self.Department_combo.setItemText(6, QCoreApplication.translate("MainWindow", u"Health Promotion", None))
        self.Department_combo.setItemText(7, QCoreApplication.translate("MainWindow", u"Information Technology", None))
        self.Department_combo.setItemText(8, QCoreApplication.translate("MainWindow", u"Laboratory", None))
        self.Department_combo.setItemText(9, QCoreApplication.translate("MainWindow", u"Medical Records", None))
        self.Department_combo.setItemText(10, QCoreApplication.translate("MainWindow", u"Office of Environmental Health", None))
        self.Department_combo.setItemText(11, QCoreApplication.translate("MainWindow", u"Optometry", None))
        self.Department_combo.setItemText(12, QCoreApplication.translate("MainWindow", u"Patient Business Office", None))
        self.Department_combo.setItemText(13, QCoreApplication.translate("MainWindow", u"Pharmacy", None))
        self.Department_combo.setItemText(14, QCoreApplication.translate("MainWindow", u"Physical Therapy", None))
        self.Department_combo.setItemText(15, QCoreApplication.translate("MainWindow", u"Primary Care", None))
        self.Department_combo.setItemText(16, QCoreApplication.translate("MainWindow", u"Property and Supply", None))
        self.Department_combo.setItemText(17, QCoreApplication.translate("MainWindow", u"Publich Health", None))
        self.Department_combo.setItemText(18, QCoreApplication.translate("MainWindow", u"Purchased Referred Care", None))
        self.Department_combo.setItemText(19, QCoreApplication.translate("MainWindow", u"Quality", None))
        self.Department_combo.setItemText(20, QCoreApplication.translate("MainWindow", u"Security", None))
        self.Department_combo.setItemText(21, QCoreApplication.translate("MainWindow", u"Social Services", None))

        self.Fit_testing_checkbox.setText(QCoreApplication.translate("MainWindow", u"Yes", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("MainWindow", u"Name", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("MainWindow", u"Department", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("MainWindow", u"Start Date", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("MainWindow", u"Annual Training Complete", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("MainWindow", u"Fit Testing", None));
        ___qtablewidgetitem5 = self.tableWidget.horizontalHeaderItem(5)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("MainWindow", u"Audit", None));
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Fit Testing Date", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"PPE Audit Date", None))
        self.Search_btn.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Last Name", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Start Date", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"PPE Audit", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Annual Complete", None))
        self.PPE_Audit_checkbox.setText(QCoreApplication.translate("MainWindow", u"Yes", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Model #", None))
        self.Save_btn.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.load_btn.setText(QCoreApplication.translate("MainWindow", u"Load", None))
        self.delete_btn.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Employee info", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Reports", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"test", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
    # retranslateUi

